// <auto-generated />
using System;
using Controle_Imob_Clientes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Controle_Imob_Clientes.Migrations
{
    [DbContext(typeof(ImobClienteContext))]
    [Migration("20241027173422_atualizar_tipo_CPF_Cliente")]
    partial class atualizar_tipo_CPF_Cliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Controle_Imob_Clientes.Models.Cliente", b =>
                {
                    b.Property<long?>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CPF")
                        .HasColumnType("bigint");

                    b.Property<string>("Casa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("imobiliariaID")
                        .HasColumnType("bigint");

                    b.HasKey("ClienteID");

                    b.HasIndex("imobiliariaID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Controle_Imob_Clientes.Models.Imobiliaria", b =>
                {
                    b.Property<long?>("imobiliariaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfilInstagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Telefone")
                        .HasColumnType("bigint");

                    b.HasKey("imobiliariaID");

                    b.ToTable("Imobiliarias");
                });

            modelBuilder.Entity("Controle_Imob_Clientes.Models.Cliente", b =>
                {
                    b.HasOne("Controle_Imob_Clientes.Models.Imobiliaria", "Imobiliaria")
                        .WithMany("Clientes")
                        .HasForeignKey("imobiliariaID");
                });
#pragma warning restore 612, 618
        }
    }
}
